# Generated by Django 4.2.6 on 2023-10-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_boardmember_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
