# Generated by Django 4.2.6 on 2023-10-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_boardmember_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
